import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Dummy from '../components/dummy.js'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
        .styled-jsx-span{
          color: red;
        }
        `}
      </style>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keyword" content="nextjs, hunting coder, blog, hunting blog, coding blog, coding error, coding tips, tech, technology" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className='py-4 flex items-center justify-center w-full'>
        <ul className='flex justify-center items-center'>
          <li className="px-4 text-lg hover:text-black text-gray-500">
            <Link href="/" scroll={false}>
              <a>Home</a>
            </Link>
          </li>
          <li className="px-4 text-lg hover:text-black text-gray-500">
            <Link href="/about" scroll={false}>
              <a>About</a>
            </Link>
          </li>
          <li className="px-4 text-lg hover:text-black text-gray-500">
            <Link href="/contact" scroll={false}>
              <a>Contact</a>
            </Link>
          </li>
          <li className="px-4 text-lg hover:text-black text-gray-500">
            <Link href="/blogs" scroll={false}>
              <a>Blogs</a>
            </Link>
          </li>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className='text-blue-500 text-4xl'>
          Hunting coder🌝
        </h1>

        <span className='styled-jsx-span mx-auto my-dummy'>😍❤😁😎🤞💋emogie😍❤😁😎🤞💋</span>
        <Dummy />

        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

        <div>
          <h2>Popular blogs</h2>
          <div className="my-4
          ">
            <h4>how to learn javascript</h4>
            <p>javascript is a scripting language to design the logic for the web</p>
          </div>
          <div className="my-4
          ">
            <h4>how to learn javascript</h4>
            <p>javascript is a scripting language to design the logic for the web</p>
          </div>
          <div className="my-4
          ">
            <h4>how to learn javascript</h4>
            <p>javascript is a scripting language to design the logic for the web</p>
          </div>
          <div className="my-4
          ">
            <h4>how to learn javascript</h4>
            <p>javascript is a scripting language to design the logic for the web</p>
          </div>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
