import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
        .styled-jsx-span{
          color: red;
        }
        `}
      </style>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keyword" content="nextjs, hunting coder, blog, hunting blog, coding blog, coding error, coding tips, tech, technology" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className='text-blue-500 text-4xl'>
          Hunting coder🌝
        </h1>

        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

        <div>
          <h2 className='text-2xl font-bold'>Popular blogs</h2>
          <Link href={'/blogpost/how to learn javascript'}>
            <div className="my-10">
              <h4 className='text-xl font-semibold'>how to learn javascript</h4>
              <p>javascript is a scripting language to design the logic for the web</p>
            </div>
          </Link>
          <Link href={'/blogpost/how to learn nextjs'}>
            <div className="my-10">
              <h4 className='text-xl font-semibold'>how to learn nextjs</h4>
              <p>javascript is a scripting language to design the logic for the web</p>
            </div>
          </Link>
          <Link href={'/blogpost/how to learn python'}>
            <div className="my-10">
              <h4 className='text-xl font-semibold'>how to learn python</h4>
              <p>javascript is a scripting language to design the logic for the web</p>
            </div>
          </Link>
          <Link href={'/blogpost/how to learn solidity'}>
            <div className="my-10">
              <h4 className='text-xl font-semibold'>how to learn solidity</h4>
              <p>javascript is a scripting language to design the logic for the web</p>
            </div>
          </Link>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
