import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div className="relative top-20 left-0 w-screen">
    <div className='flex flex-col justify-start items-center'>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keyword" content="nextjs, hunting coder, blog, hunting blog, coding blog, coding error, coding tips, tech, technology" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
        <h1 className='text-blue-500 text-4xl text-center'>
          Hunting coder🌝
        </h1>

        <p className=' text-center mt-4'>
          A blog for hunting coders by a hunting coder
        </p>

        <div>
          <h2 className='text-2xl font-bold text-center mt-4'>Popular blogs</h2>
          <Link href={'/blogpost/how to learn javascript'}>
            <div className="my-10">
              <h4 className='text-xl font-semibold'>how to learn javascript</h4>
              <p>javascript is a scripting language to design the logic for the web</p>
            </div>
          </Link>
          <Link href={'/blogpost/how to learn nextjs'}>
            <div className="my-10">
              <h4 className='text-xl font-semibold'>how to learn nextjs</h4>
              <p>javascript is a scripting language to design the logic for the web</p>
            </div>
          </Link>
          <Link href={'/blogpost/how to learn python'}>
            <div className="my-10">
              <h4 className='text-xl font-semibold'>how to learn python</h4>
              <p>javascript is a scripting language to design the logic for the web</p>
            </div>
          </Link>
          <Link href={'/blogpost/how to learn solidity'}>
            <div className="my-10">
              <h4 className='text-xl font-semibold'>how to learn solidity</h4>
              <p>javascript is a scripting language to design the logic for the web</p>
            </div>
          </Link>
        </div>

      </main>
    </div>
    </div>
  )
}
